// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.14.0
// source: item_products.proto

package itemProductspb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CategoryIdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ReqCategoryId uint32 `protobuf:"varint,1,opt,name=req_category_id,json=reqCategoryId,proto3" json:"req_category_id,omitempty"`
}

func (x *CategoryIdRequest) Reset() {
	*x = CategoryIdRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_item_products_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CategoryIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategoryIdRequest) ProtoMessage() {}

func (x *CategoryIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_item_products_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategoryIdRequest.ProtoReflect.Descriptor instead.
func (*CategoryIdRequest) Descriptor() ([]byte, []int) {
	return file_item_products_proto_rawDescGZIP(), []int{0}
}

func (x *CategoryIdRequest) GetReqCategoryId() uint32 {
	if x != nil {
		return x.ReqCategoryId
	}
	return 0
}

type ItemListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ListaItems []*Item `protobuf:"bytes,1,rep,name=lista_items,json=listaItems,proto3" json:"lista_items,omitempty"`
}

func (x *ItemListResponse) Reset() {
	*x = ItemListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_item_products_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ItemListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemListResponse) ProtoMessage() {}

func (x *ItemListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_item_products_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemListResponse.ProtoReflect.Descriptor instead.
func (*ItemListResponse) Descriptor() ([]byte, []int) {
	return file_item_products_proto_rawDescGZIP(), []int{1}
}

func (x *ItemListResponse) GetListaItems() []*Item {
	if x != nil {
		return x.ListaItems
	}
	return nil
}

type ItemStatusResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StatusSuccessful bool `protobuf:"varint,1,opt,name=status_successful,json=statusSuccessful,proto3" json:"status_successful,omitempty"`
}

func (x *ItemStatusResponse) Reset() {
	*x = ItemStatusResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_item_products_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ItemStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemStatusResponse) ProtoMessage() {}

func (x *ItemStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_item_products_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemStatusResponse.ProtoReflect.Descriptor instead.
func (*ItemStatusResponse) Descriptor() ([]byte, []int) {
	return file_item_products_proto_rawDescGZIP(), []int{2}
}

func (x *ItemStatusResponse) GetStatusSuccessful() bool {
	if x != nil {
		return x.StatusSuccessful
	}
	return false
}

type Item struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Category    string  `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"`
	ItemId      uint32  `protobuf:"varint,2,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	CategoryId  uint32  `protobuf:"varint,3,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	NombreItem  string  `protobuf:"bytes,4,opt,name=nombre_item,json=nombreItem,proto3" json:"nombre_item,omitempty"`
	ImageName   string  `protobuf:"bytes,5,opt,name=image_name,json=imageName,proto3" json:"image_name,omitempty"`
	Descripcion string  `protobuf:"bytes,6,opt,name=descripcion,proto3" json:"descripcion,omitempty"`
	ItemPrice   float32 `protobuf:"fixed32,7,opt,name=item_price,json=itemPrice,proto3" json:"item_price,omitempty"`
}

func (x *Item) Reset() {
	*x = Item{}
	if protoimpl.UnsafeEnabled {
		mi := &file_item_products_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Item) ProtoMessage() {}

func (x *Item) ProtoReflect() protoreflect.Message {
	mi := &file_item_products_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Item.ProtoReflect.Descriptor instead.
func (*Item) Descriptor() ([]byte, []int) {
	return file_item_products_proto_rawDescGZIP(), []int{3}
}

func (x *Item) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *Item) GetItemId() uint32 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

func (x *Item) GetCategoryId() uint32 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *Item) GetNombreItem() string {
	if x != nil {
		return x.NombreItem
	}
	return ""
}

func (x *Item) GetImageName() string {
	if x != nil {
		return x.ImageName
	}
	return ""
}

func (x *Item) GetDescripcion() string {
	if x != nil {
		return x.Descripcion
	}
	return ""
}

func (x *Item) GetItemPrice() float32 {
	if x != nil {
		return x.ItemPrice
	}
	return 0
}

var File_item_products_proto protoreflect.FileDescriptor

var file_item_products_proto_rawDesc = []byte{
	0x0a, 0x13, 0x69, 0x74, 0x65, 0x6d, 0x5f, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x73, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x1d, 0x69, 0x74, 0x65, 0x6d, 0x5f, 0x70, 0x72, 0x6f, 0x64,
	0x75, 0x63, 0x74, 0x73, 0x5f, 0x70, 0x62, 0x2e, 0x69, 0x74, 0x65, 0x6d, 0x50, 0x72, 0x6f, 0x64,
	0x75, 0x63, 0x74, 0x73, 0x22, 0x3b, 0x0a, 0x11, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79,
	0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x26, 0x0a, 0x0f, 0x72, 0x65, 0x71,
	0x5f, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x0d, 0x72, 0x65, 0x71, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x49,
	0x64, 0x22, 0x58, 0x0a, 0x10, 0x49, 0x74, 0x65, 0x6d, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x44, 0x0a, 0x0b, 0x6c, 0x69, 0x73, 0x74, 0x61, 0x5f, 0x69,
	0x74, 0x65, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x69, 0x74, 0x65,
	0x6d, 0x5f, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x73, 0x5f, 0x70, 0x62, 0x2e, 0x69, 0x74,
	0x65, 0x6d, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x73, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x52,
	0x0a, 0x6c, 0x69, 0x73, 0x74, 0x61, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x22, 0x41, 0x0a, 0x12, 0x49,
	0x74, 0x65, 0x6d, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x2b, 0x0a, 0x11, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x5f, 0x73, 0x75, 0x63, 0x63,
	0x65, 0x73, 0x73, 0x66, 0x75, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x10, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x66, 0x75, 0x6c, 0x22, 0xdd,
	0x01, 0x0a, 0x04, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67,
	0x6f, 0x72, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67,
	0x6f, 0x72, 0x79, 0x12, 0x17, 0x0a, 0x07, 0x69, 0x74, 0x65, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x69, 0x74, 0x65, 0x6d, 0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b,
	0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x0a, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x49, 0x64, 0x12, 0x1f, 0x0a,
	0x0b, 0x6e, 0x6f, 0x6d, 0x62, 0x72, 0x65, 0x5f, 0x69, 0x74, 0x65, 0x6d, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0a, 0x6e, 0x6f, 0x6d, 0x62, 0x72, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x1d,
	0x0a, 0x0a, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a,
	0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x63, 0x69, 0x6f, 0x6e, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x63, 0x69, 0x6f, 0x6e, 0x12,
	0x1d, 0x0a, 0x0a, 0x69, 0x74, 0x65, 0x6d, 0x5f, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x02, 0x52, 0x09, 0x69, 0x74, 0x65, 0x6d, 0x50, 0x72, 0x69, 0x63, 0x65, 0x32, 0xeb,
	0x01, 0x0a, 0x0d, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x6f, 0x53, 0x74, 0x6f, 0x63, 0x6b,
	0x12, 0x74, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x73, 0x4c,
	0x69, 0x73, 0x74, 0x12, 0x30, 0x2e, 0x69, 0x74, 0x65, 0x6d, 0x5f, 0x70, 0x72, 0x6f, 0x64, 0x75,
	0x63, 0x74, 0x73, 0x5f, 0x70, 0x62, 0x2e, 0x69, 0x74, 0x65, 0x6d, 0x50, 0x72, 0x6f, 0x64, 0x75,
	0x63, 0x74, 0x73, 0x2e, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x49, 0x64, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2f, 0x2e, 0x69, 0x74, 0x65, 0x6d, 0x5f, 0x70, 0x72, 0x6f,
	0x64, 0x75, 0x63, 0x74, 0x73, 0x5f, 0x70, 0x62, 0x2e, 0x69, 0x74, 0x65, 0x6d, 0x50, 0x72, 0x6f,
	0x64, 0x75, 0x63, 0x74, 0x73, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x64, 0x0a, 0x0a, 0x53, 0x65, 0x74, 0x50, 0x72, 0x6f,
	0x64, 0x75, 0x63, 0x74, 0x12, 0x23, 0x2e, 0x69, 0x74, 0x65, 0x6d, 0x5f, 0x70, 0x72, 0x6f, 0x64,
	0x75, 0x63, 0x74, 0x73, 0x5f, 0x70, 0x62, 0x2e, 0x69, 0x74, 0x65, 0x6d, 0x50, 0x72, 0x6f, 0x64,
	0x75, 0x63, 0x74, 0x73, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x1a, 0x31, 0x2e, 0x69, 0x74, 0x65, 0x6d,
	0x5f, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x73, 0x5f, 0x70, 0x62, 0x2e, 0x69, 0x74, 0x65,
	0x6d, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x73, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x1f, 0x5a, 0x1d,
	0x69, 0x74, 0x65, 0x6d, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x73, 0x70, 0x62, 0x3b, 0x69,
	0x74, 0x65, 0x6d, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x73, 0x70, 0x62, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_item_products_proto_rawDescOnce sync.Once
	file_item_products_proto_rawDescData = file_item_products_proto_rawDesc
)

func file_item_products_proto_rawDescGZIP() []byte {
	file_item_products_proto_rawDescOnce.Do(func() {
		file_item_products_proto_rawDescData = protoimpl.X.CompressGZIP(file_item_products_proto_rawDescData)
	})
	return file_item_products_proto_rawDescData
}

var file_item_products_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_item_products_proto_goTypes = []interface{}{
	(*CategoryIdRequest)(nil),  // 0: item_products_pb.itemProducts.CategoryIdRequest
	(*ItemListResponse)(nil),   // 1: item_products_pb.itemProducts.ItemListResponse
	(*ItemStatusResponse)(nil), // 2: item_products_pb.itemProducts.ItemStatusResponse
	(*Item)(nil),               // 3: item_products_pb.itemProducts.Item
}
var file_item_products_proto_depIdxs = []int32{
	3, // 0: item_products_pb.itemProducts.ItemListResponse.lista_items:type_name -> item_products_pb.itemProducts.Item
	0, // 1: item_products_pb.itemProducts.ProductoStock.GetProductsList:input_type -> item_products_pb.itemProducts.CategoryIdRequest
	3, // 2: item_products_pb.itemProducts.ProductoStock.SetProduct:input_type -> item_products_pb.itemProducts.Item
	1, // 3: item_products_pb.itemProducts.ProductoStock.GetProductsList:output_type -> item_products_pb.itemProducts.ItemListResponse
	2, // 4: item_products_pb.itemProducts.ProductoStock.SetProduct:output_type -> item_products_pb.itemProducts.ItemStatusResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_item_products_proto_init() }
func file_item_products_proto_init() {
	if File_item_products_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_item_products_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CategoryIdRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_item_products_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ItemListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_item_products_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ItemStatusResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_item_products_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Item); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_item_products_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_item_products_proto_goTypes,
		DependencyIndexes: file_item_products_proto_depIdxs,
		MessageInfos:      file_item_products_proto_msgTypes,
	}.Build()
	File_item_products_proto = out.File
	file_item_products_proto_rawDesc = nil
	file_item_products_proto_goTypes = nil
	file_item_products_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ProductoStockClient is the client API for ProductoStock service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ProductoStockClient interface {
	GetProductsList(ctx context.Context, in *CategoryIdRequest, opts ...grpc.CallOption) (*ItemListResponse, error)
	SetProduct(ctx context.Context, in *Item, opts ...grpc.CallOption) (*ItemStatusResponse, error)
}

type productoStockClient struct {
	cc grpc.ClientConnInterface
}

func NewProductoStockClient(cc grpc.ClientConnInterface) ProductoStockClient {
	return &productoStockClient{cc}
}

func (c *productoStockClient) GetProductsList(ctx context.Context, in *CategoryIdRequest, opts ...grpc.CallOption) (*ItemListResponse, error) {
	out := new(ItemListResponse)
	err := c.cc.Invoke(ctx, "/item_products_pb.itemProducts.ProductoStock/GetProductsList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productoStockClient) SetProduct(ctx context.Context, in *Item, opts ...grpc.CallOption) (*ItemStatusResponse, error) {
	out := new(ItemStatusResponse)
	err := c.cc.Invoke(ctx, "/item_products_pb.itemProducts.ProductoStock/SetProduct", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProductoStockServer is the server API for ProductoStock service.
type ProductoStockServer interface {
	GetProductsList(context.Context, *CategoryIdRequest) (*ItemListResponse, error)
	SetProduct(context.Context, *Item) (*ItemStatusResponse, error)
}

// UnimplementedProductoStockServer can be embedded to have forward compatible implementations.
type UnimplementedProductoStockServer struct {
}

func (*UnimplementedProductoStockServer) GetProductsList(context.Context, *CategoryIdRequest) (*ItemListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProductsList not implemented")
}
func (*UnimplementedProductoStockServer) SetProduct(context.Context, *Item) (*ItemStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetProduct not implemented")
}

func RegisterProductoStockServer(s *grpc.Server, srv ProductoStockServer) {
	s.RegisterService(&_ProductoStock_serviceDesc, srv)
}

func _ProductoStock_GetProductsList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CategoryIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductoStockServer).GetProductsList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/item_products_pb.itemProducts.ProductoStock/GetProductsList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductoStockServer).GetProductsList(ctx, req.(*CategoryIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductoStock_SetProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Item)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductoStockServer).SetProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/item_products_pb.itemProducts.ProductoStock/SetProduct",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductoStockServer).SetProduct(ctx, req.(*Item))
	}
	return interceptor(ctx, in, info, handler)
}

var _ProductoStock_serviceDesc = grpc.ServiceDesc{
	ServiceName: "item_products_pb.itemProducts.ProductoStock",
	HandlerType: (*ProductoStockServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetProductsList",
			Handler:    _ProductoStock_GetProductsList_Handler,
		},
		{
			MethodName: "SetProduct",
			Handler:    _ProductoStock_SetProduct_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "item_products.proto",
}
